version: '3.8'

services:
  # Vector Database Service - ChromaDB
  chromadb:
    image: chromadb/chroma:latest
    container_name: openmanus_chromadb
    ports:
      - "8001:8000"  # ChromaDB default port
    volumes:
      - chromadb_data:/chroma/chroma
      - ./config/chromadb:/chroma/config
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:3000", "http://localhost:8000"]
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=${CHROMA_AUTH_PROVIDER:-}
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_AUTH_CREDENTIALS:-}
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=${CHROMA_AUTH_HEADER:-X-Chroma-Token}
    networks:
      - openmanus_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - VECTOR_DB_HOST=${VECTOR_DB_HOST:-chromadb}
      - VECTOR_DB_PORT=${VECTOR_DB_PORT:-8000}
      - VECTOR_DB_URL=${VECTOR_DB_URL:-http://chromadb:8000}
      - CHROMA_HOST=${CHROMA_HOST:-chromadb}
      - CHROMA_PORT=${CHROMA_PORT:-8000}
      - CHROMA_AUTH_TOKEN=${CHROMA_AUTH_TOKEN:-}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - openmanus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
      - REACT_APP_VECTOR_DB_URL=${REACT_APP_VECTOR_DB_URL:-http://localhost:8001}
    depends_on:
      - backend
    networks:
      - openmanus-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - openmanus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL for production database (optional)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=openmanus
      - POSTGRES_USER=openmanus
      - POSTGRES_PASSWORD=openmanus_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - openmanus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openmanus"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - openmanus-network

volumes:
  redis_data:
  postgres_data:
  chromadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/chromadb

networks:
  openmanus-network:
    driver: bridge
