[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --tb=short"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
filterwarnings = ["ignore::DeprecationWarning"]

[tool.ruff]
# Increased line length for modern development practices
line-length = 120
indent-width = 4

# Assume Python 3.11+
target-version = "py311"

# Include notebooks
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]

# Exclude a variety of commonly ignored directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[tool.ruff.lint]
# Enable comprehensive linting rules for modern Python development
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-comprehensions
    "C4",
    # flake8-unused-arguments
    "ARG",
    # flake8-use-pathlib
    "PTH",
    # flake8-quotes
    "Q",
    # flake8-return
    "RET",
    # flake8-raise
    "RSE",
    # flake8-type-checking
    "TCH",
    # pydocstyle
    "D",
    # flake8-annotations
    "ANN",
    # flake8-async
    "ASYNC",
    # flake8-bandit (security)
    "S",
    # flake8-logging-format
    "G",
    # pylint
    "PL",
    # Ruff-specific rules
    "RUF",
]

# Ignore specific rules that can be too strict for this project
ignore = [
    # Missing docstring in public module/class/method/function
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    # Docstring formatting issues that are too strict
    "D200",
    "D212",
    "D400",
    "D401",
    "D415",
    # Missing type annotations (can be too strict for existing code)
    "ANN101",
    "ANN102",
    "ANN201",
    "ANN202",
    "ANN204",
    "ANN206",
    # Security issues that are false positives in this context
    "S101", # Use of assert
    "S102", # Use of exec detected
    "S104", # Possible binding to all interfaces
    "S108", # Probable insecure usage of temp file/directory
    "S110", # try-except-pass detected
    "S112", # try-except-continue detected
    "S202", # Uses of tarfile.extractall()
    "S311", # Standard pseudo-random generators
    "S603", # subprocess call: check for execution of untrusted input
    "S607", # Starting a process with a partial executable path
    # Pylint rules that can be too opinionated
    "PLR0913", # Too many arguments
    "PLR0915", # Too many statements
    "PLR2004", # Magic value used in comparison
    "PLW2901", # Redefined loop variable
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, longer lines, and imports after pytest.importorskip
"tests/**/*.py" = ["PLR2004", "S101", "E501", "E402", "ANN", "D"]
# __init__.py files can have unused imports
"__init__.py" = ["F401"]
# FastAPI files can use function calls in default arguments (Depends, File, Query)
"app/api/**/*.py" = ["B008"]
# Prompt files can have longer lines for readability
"app/prompt/**/*.py" = ["E501"]
# Tool files can have longer description strings
"app/tool/**/*.py" = ["E501"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = false

# Set the line length limit used for formatting and line length violations.
docstring-code-line-length = "dynamic"
