# Ruff configuration for OpenManus backend
line-length = 120
indent-width = 4
target-version = "py311"

include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "temp_files",
    "uploads",
    "logs",
]

[lint]
select = [
    "E",
    "W",
    "F",
    "UP",
    "B",
    "SIM",
    "I",
    "C4",
    "ARG",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "TCH",
    "D",
    "S",
    "PL",
    "RUF",
]

ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D203",
    "D212",
    "D400",
    "D401",
    "D415",
    "S101",
    "S102",
    "S104",
    "S108",
    "S202",
    "S311",
    "S603",
    "S607",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLW2901",
    "PLR0911",
    "PLR0912",
]

fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"tests/**/*.py" = ["PLR2004", "S101", "E501", "E402", "D", "ARG"]
"__init__.py" = ["F401", "F403"]
"app/api/**/*.py" = ["B008"]
"app/prompt/**/*.py" = ["E501"]
"app/tool/**/*.py" = ["E501"]
"app/config/**/*.py" = ["S105", "S106"]
"demos/**/*.py" = ["T201", "S101", "PLR2004"]

[lint.isort]
force-sort-within-sections = true
known-first-party = ["app"]

[lint.mccabe]
max-complexity = 10

[lint.pylint]
max-args = 8
max-locals = 20
max-branches = 12
max-statements = 50

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
